packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.1
  next: ^16.0.4
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@vercel/speed-insights"
  - cbor-extract
  - esbuild
  - sharp
  - workerd
