packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": ^24.10.9
  "@types/react": ^19.2.8
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.2
  next: ^16.1.4
  prettier: ^3.8.0
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: ^5.9.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@vercel/speed-insights"
  - cbor-extract
  - esbuild
  - sharp
  - workerd

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - "@radix-ui/*"
  - prettier-plugin-tailwindcss
