packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.10.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  eslint: ^9.39.0
  next: ^16.0.1
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - cbor-extract
  - esbuild
  - sharp
  - workerd
