packages:
  - apps/*
  - packages/*

catalog:
  "@base-ui/react": ^1.4.1
  "@tailwindcss/postcss": ^4.2.4
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^2.0.1
  "@vitejs/plugin-react": ^6.0.1
  lucide-react: ^1.14.0
  next: ^16.2.4
  postcss: ^8.5.13
  react: ^19.2.5
  react-dom: ^19.2.5
  tailwindcss: ^4.2.4
  tsx: ^4.21.0
  typescript: ^6.0.3
  vite: ^8.0.10

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@vercel/speed-insights"
  - cbor-extract
  - esbuild
  - sharp
  - workerd
