packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.6.2
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  eslint: ^9.37.0
  next: ^15.5.4
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - workerd

nodeLinker: hoisted
linkWorkspacePackages: true
