packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.5.2
  '@types/react': ^19.1.14
  '@types/react-dom': ^19.1.9
  eslint: ^9.36.0
  next: ^15.5.4
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - workerd

nodeLinker: hoisted
linkWorkspacePackages: true
