packages:
  - apps/*
  - packages/*

catalog:
  "@base-ui/react": ^1.2.0
  "@types/node": ^25.3.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^1.6.1
  "@vitejs/plugin-react": ^5.1.4
  eslint: ^9.39.3
  lucide-react: ^0.562.0
  next: ^16.1.6
  prettier: ^3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.2.0
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@vercel/speed-insights"
  - cbor-extract
  - esbuild
  - sharp
  - workerd

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
