packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.9.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  eslint: ^9.38.0
  next: ^15.5.6
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - workerd
