#!/usr/bin/env node
// Symlinks this package's skills + agents + CLAUDE.md into ~/.claude, generates
// Codex agent TOMLs into ~/.codex/agents, and merges mcp.json into ~/.claude.json.
//
// Runs on `postinstall`. Idempotent, non-destructive (real files are backed up,
// never deleted), and never throws — a failed link must not break `npm install`.
//
// Skip with KYH_SKILLS_NO_LINK=1. Preview with --dry-run (or KYH_SKILLS_DRY_RUN=1).
// Also skipped automatically in CI.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const HOME = os.homedir();
const CLAUDE_DIR = path.join(HOME, ".claude");
const CODEX_DIR = path.join(HOME, ".codex");

const DRY = process.argv.includes("--dry-run") || !!process.env.KYH_SKILLS_DRY_RUN;
const TAG = "[@kyh/skills]";
const GEN_MARKER = "# @kyh/skills generated — edits will be overwritten";

const log = (...a) => console.log(TAG, ...a);
const warn = (...a) => console.warn(TAG, ...a);

function main() {
  if (process.env.KYH_SKILLS_NO_LINK) return log("KYH_SKILLS_NO_LINK set — skipping.");
  if (process.env.CI) return log("CI detected — skipping link.");
  if (process.platform === "win32")
    warn("Windows symlinks may require admin/developer mode; continuing best-effort.");
  if (DRY) log("dry run — no changes will be written.");

  ensureDir(path.join(CLAUDE_DIR, "skills"));
  ensureDir(path.join(CLAUDE_DIR, "agents"));
  ensureDir(path.join(CODEX_DIR, "agents"));

  // Each phase is isolated: one failing phase must not skip the rest.
  step(linkSkills);
  step(linkClaudeAgents);
  step(linkClaudeMd);
  step(generateCodexAgents);
  step(mergeMcp);

  log("done.");
}

function step(fn) {
  try {
    fn();
  } catch (e) {
    warn(`${fn.name} failed: ${e?.message ?? e}`);
  }
}

// --- Claude: skills (one symlinked dir per skill) ------------------------------

function linkSkills() {
  const src = path.join(PKG_ROOT, "skills");
  if (!fs.existsSync(src)) return;
  for (const name of dirents(src, "dir"))
    symlink(path.join(src, name), path.join(CLAUDE_DIR, "skills", name), "dir");
}

// --- Claude: agents (one symlinked .md per agent) ------------------------------

function linkClaudeAgents() {
  const src = path.join(PKG_ROOT, "agents");
  if (!fs.existsSync(src)) return;
  for (const name of dirents(src, "file").filter((f) => f.endsWith(".md")))
    symlink(path.join(src, name), path.join(CLAUDE_DIR, "agents", name), "file");
}

// --- Claude: global CLAUDE.md --------------------------------------------------

function linkClaudeMd() {
  const src = path.join(PKG_ROOT, "CLAUDE.md");
  if (fs.existsSync(src)) symlink(src, path.join(CLAUDE_DIR, "CLAUDE.md"), "file");
}

// --- Codex: agents (generated TOML, not symlinked — format differs) ------------

function generateCodexAgents() {
  const src = path.join(PKG_ROOT, "agents");
  if (!fs.existsSync(src)) return;
  for (const file of dirents(src, "file").filter((f) => f.endsWith(".md"))) {
    const name = path.basename(file, ".md");
    const dest = path.join(CODEX_DIR, "agents", `${name}.toml`);
    try {
      const toml = toCodexToml(name, fs.readFileSync(path.join(src, file), "utf8"));

      if (fs.existsSync(dest) && !firstLineIs(dest, GEN_MARKER)) {
        warn(`skip codex/agents/${name}.toml — exists and not generated by us.`);
        continue;
      }
      if (DRY) {
        log(`would write ~/.codex/agents/${name}.toml`);
        continue;
      }
      fs.writeFileSync(dest, toml);
      log(`wrote ~/.codex/agents/${name}.toml`);
    } catch (e) {
      warn(`failed to write codex/agents/${name}.toml: ${e.message}`);
    }
  }
}

function toCodexToml(name, md) {
  const text = md.replace(/\r\n/g, "\n"); // tolerate CRLF checkouts
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  const front = m ? m[1] : "";
  const body = (m ? m[2] : text).trim();

  const descMatch = front.match(/^description:\s*(.*)$/m);
  const description = descMatch ? descMatch[1].trim() : `${name} agent`;
  // architect-style "*": deny means a read-only agent.
  const readOnly = /["']\*["']\s*:\s*deny/.test(front);

  // TOML basic string for description (JSON escaping is a valid subset);
  // multi-line literal ''' for instructions so backslashes pass through verbatim.
  const desc = JSON.stringify(description);
  const instr = body.replace(/'''/g, "''");
  const lines = [GEN_MARKER, `name = ${JSON.stringify(name)}`, `description = ${desc}`];
  if (readOnly) lines.push(`sandbox_mode = "read-only"`);
  lines.push(`developer_instructions = '''\n${instr}\n'''`);
  return lines.join("\n") + "\n";
}

// --- MCP: merge into ~/.claude.json mcpServers ---------------------------------

function mergeMcp() {
  const src = path.join(PKG_ROOT, "mcp.json");
  if (!fs.existsSync(src)) return;

  let servers;
  try {
    servers = JSON.parse(fs.readFileSync(src, "utf8")).mcpServers || {};
  } catch (e) {
    return warn(`could not parse mcp.json: ${e.message}`);
  }
  const names = Object.keys(servers);
  if (names.length === 0) return;

  const dest = path.join(HOME, ".claude.json");
  let config = {};
  if (fs.existsSync(dest)) {
    try {
      config = JSON.parse(fs.readFileSync(dest, "utf8"));
    } catch (e) {
      return warn(`~/.claude.json is not valid JSON — skipping MCP merge (${e.message}).`);
    }
  }
  config.mcpServers = { ...config.mcpServers, ...servers };

  if (DRY) return log(`would merge mcpServers into ~/.claude.json: ${names.join(", ")}`);
  fs.writeFileSync(dest, JSON.stringify(config, null, 2) + "\n");
  log(`merged mcpServers into ~/.claude.json: ${names.join(", ")}`);
}

// --- helpers -------------------------------------------------------------------

function symlink(src, dest, type) {
  const rel = dest.replace(HOME, "~");
  try {
    if (fs.existsSync(dest) || isSymlink(dest)) {
      if (isSymlink(dest) && samePath(dest, src)) return; // already linked
      if (isSymlink(dest)) {
        if (DRY) return log(`would relink ${rel}`);
        fs.unlinkSync(dest);
      } else {
        const bak = backupPath(dest);
        if (DRY) return log(`would back up ${rel} -> ${path.basename(bak)} and link`);
        fs.renameSync(dest, bak);
        warn(`backed up existing ${rel} -> ${path.basename(bak)}`);
      }
    } else if (DRY) {
      return log(`would link ${rel}`);
    }
    fs.symlinkSync(src, dest, type === "dir" ? "dir" : "file");
    log(`linked ${rel}`);
  } catch (e) {
    warn(`failed to link ${rel}: ${e.message}`);
  }
}

function ensureDir(p) {
  if (DRY || fs.existsSync(p)) return;
  fs.mkdirSync(p, { recursive: true });
}

function dirents(dir, kind) {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => (kind === "dir" ? d.isDirectory() : d.isFile()))
    .map((d) => d.name);
}

function isSymlink(p) {
  try {
    return fs.lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

function samePath(a, b) {
  try {
    return fs.realpathSync(a) === fs.realpathSync(b);
  } catch {
    return false;
  }
}

function firstLineIs(p, expected) {
  try {
    return fs.readFileSync(p, "utf8").split("\n", 1)[0].trim() === expected;
  } catch {
    return false;
  }
}

function backupPath(p) {
  let bak = `${p}.bak`;
  if (fs.existsSync(bak)) bak = `${p}.bak-${Date.now()}`;
  return bak;
}

try {
  main();
} catch (e) {
  // Never fail the install.
  warn(`unexpected error: ${e?.message ?? e}`);
}
