name = "kyh-partyserver"
main = 'src/server.ts'
compatibility_date = "2024-07-25"

[[durable_objects.bindings]]
name = "KyhServer"
class_name = "KyhServer"

[[migrations]]
tag = "v1"
new_classes = ["KyhServer"]
